import type { Metadata } from "next";
import "./../../globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Mystry messages-Dashboard",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      
      <Navbar />
      {children}
      
    </div>
  
  );
}
